### PR TITLE
Rename doc files to be consistent with main inspec project

### PR DESCRIPTION
**Pull request by clintoncwolfe**
This simply renames all documentation files to end in `.md.erb`, as used by the core inspec project.  This will enable InSpec core to build docs from inspec-gcp.

### CODE REVIEW

**Comment by skpaterson** [comment]
Hi @clintoncwolfe - these were originally `.md.erb` but changed to markdown as per your suggestion in #17.  Given these are currently useful as markdown wouldn't it be better to perform a renaming as part of the future merge to InSpec core?

**Comment by skpaterson** [comment]
Having now seen https://github.com/inspec/inspec/pull/3184 I understand more of the context.  Can I suggest a best of both worlds approach where the regexp InSpec Core side includes both `*.md` and `*.md.erb` if present?

**Comment by davymcaleer** [comment]
@clintoncwolfe - I'd go with what Stuart suggestion

**Comment by clintoncwolfe** [comment]
Moot.

**Pull request closed without merging**
