### PR TITLE
Add ability to test individual as well as multiple organisations

### PR DESCRIPTION
**Pull request by walterdolce**
I wasn't really sure how I should have gone about testing this as you need to have a G Suite account for this (and I did not want to use the company one), but I promise everything works. I have a screenshot for it! 😛 

screenshot_2019-02-20_at_17_15_10

### CODE REVIEW

**Comment by walterdolce** [comment]
The above is based on:
```
  describe google_organizations do
    it { should exist }
  end

  google_organizations.where(display_name: 'myorg.com').names.each do |name|
    describe google_organization(name: name) do
      it { should exist }
      its('lifecycle_state') { should eq 'ACTIVE' }
    end
  end
```

**Comment by walterdolce** [comment]
@skpaterson sounds good. Done!

**Comment by skpaterson** [comment]
Brilliant, thanks again.  For completeness do you mind adding the control for the singular `google_organization` resource and we're good to go?

**Comment by walterdolce** [comment]
@skpaterson certainly. Also done!

**Pull request merged**
