### PR TITLE
Add support for regional Google compute disk

### LINKED ISSUE #163: Add support for regional google_compute_disk
## Detailed Description
`google_compute_disk` only supports zonal disks instead of supporting both zonal and regional disks.

## Context
When verifying the status of Google Cloud persistent disk, one should be able to test all types of disks. Not just zonal disks.

## Possible Implementation
Not sure. The attribute `zone` might get in the way of this though, I suspect.

### PR DESCRIPTION
**Pull request by walterdolce**
Signed-off-by: Walter Dolce <walterdolce@gmail.com>

### Description
This PR adds support for verifying the state of regional disks. 

### Issues Resolved
#163

PS: changing the table in the README is a nightmare 😅

### CODE REVIEW

**Comment by skpaterson** [comment]
Thanks for this @walterdolce !  To resolve the build failure, rebasing against master and making the following minor change should allow us to proceed e.g.

```
libraries/google_compute_regional_disk.rb:1:1: C: Style/FrozenStringLiteralComment: Missing magic comment # frozen_string_literal: true.
```

Apologies for the pain editing the markdown table, I generate this automatically based on the files in the docs directory.  Should probably commit that script somewhere and update the docs...

**Comment by walterdolce** [comment]
> Missing magic comment
A comment that causes a build to fail? 🤔 Is that expected? 

I'll do as instructed in the meantime.

> Should probably commit that script somewhere and update the docs...
That would be great 😄

**Comment by walterdolce** [comment]
@skpaterson all done!

**Comment by skpaterson** [comment]
Awesome, thanks @walterdolce.

**Pull request merged**
